# -*- coding: utf-8 -*-
"""water demand forecasting app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sl-oISNWUTBmYhQzULw-mWr0nUcgzzcZ
"""

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import plotly.graph_objects as go

st.set_page_config(page_title="AI Water Demand Forecasting", layout="wide")

st.title("💧 AI-Based Water Demand Forecasting & Pump Optimization")

st.write("This dashboard forecasts water demand and simulates pump optimization for sustainable water management.")

st.markdown("""
### Project Objective
This AI system forecasts future water demand and simulates optimized pumping schedules to reduce energy consumption and over-pumping in institutional environments.

The system demonstrates how machine learning and predictive analytics can support sustainable water resource management.
""")

# Load dataset
df = pd.read_csv("global_water_consumption_2000_2025.csv")

# Country Selection
country = st.selectbox("🌍 Select Country", df["Country"].unique())

country_df = df[df["Country"] == country].copy()
country_df = country_df.sort_values("Year")

# Create lag features
country_df["Lag_1"] = country_df["Total Water Consumption (Billion m3)"].shift(1)
country_df["Lag_2"] = country_df["Total Water Consumption (Billion m3)"].shift(2)

country_df = country_df.dropna()

X = country_df[["Lag_1", "Lag_2"]]
y = country_df["Total Water Consumption (Billion m3)"]

# Train model
model = LinearRegression()
model.fit(X, y)

# Forecast slider
future_years = st.slider("📅 Forecast Years", 1, 10, 5)

last_values = X.iloc[-1].values.reshape(1, -1)

future_predictions = []

for i in range(future_years):
    next_pred = model.predict(last_values)[0]
    future_predictions.append(next_pred)
    last_values = np.array([[next_pred, last_values[0][0]]])

future_year_list = list(range(country_df["Year"].max()+1,
                              country_df["Year"].max()+1+future_years))

future_df = pd.DataFrame({
    "Year": future_year_list,
    "Forecasted Consumption": future_predictions
})

# Pump Optimization
optimization = st.slider("⚙ Pump Optimization (%)", 0, 30, 10)

future_df["Optimized Consumption"] = future_df["Forecasted Consumption"] * (1 - optimization/100)

# Calculations
water_saved = future_df["Forecasted Consumption"] - future_df["Optimized Consumption"]

electricity_saved = water_saved * 0.5
carbon_saved = electricity_saved * 0.82

# KPI Metrics
st.subheader("📊 Key Sustainability Metrics")

col1, col2, col3, col4 = st.columns(4)

col1.metric(
    "💧 Total Water Consumption",
    f"{round(country_df['Total Water Consumption (Billion m3)'].sum(),2)} B m³"
)

forecast_growth = ((future_df["Forecasted Consumption"].mean() -
                   country_df["Total Water Consumption (Billion m3)"].mean())
                   / country_df["Total Water Consumption (Billion m3)"].mean()) * 100

col2.metric(
    "📈 Forecast Growth %",
    f"{round(forecast_growth,2)}%"
)

col3.metric(
    "🚰 Water Saved",
    f"{round(water_saved.sum(),2)} B m³"
)

col4.metric(
    "🌱 Carbon Reduction",
    f"{round(carbon_saved.sum(),2)} kg CO₂"
)

# Interactive Plotly Graph
st.subheader("🌍 Interactive Water Demand Forecast Dashboard")

fig = go.Figure()

# Historical
fig.add_trace(go.Scatter(
    x=country_df["Year"],
    y=country_df["Total Water Consumption (Billion m3)"],
    mode='lines+markers',
    name='Historical Consumption'
))

# Forecast
fig.add_trace(go.Scatter(
    x=future_df["Year"],
    y=future_df["Forecasted Consumption"],
    mode='lines+markers',
    name='Forecasted Demand'
))

# Optimized
fig.add_trace(go.Scatter(
    x=future_df["Year"],
    y=future_df["Optimized Consumption"],
    mode='lines+markers',
    name='Optimized Consumption'
))

fig.update_layout(
    title="AI Water Demand Forecast with Pump Optimization",
    xaxis_title="Year",
    yaxis_title="Water Consumption (Billion m³)",
    template="plotly_white"
)

st.plotly_chart(fig, use_container_width=True)

# Energy Simulation
st.subheader("⚡ Energy Savings Simulation")

st.write("Estimated Electricity Savings (kWh):", round(electricity_saved.sum(),2))
st.write("Estimated Carbon Reduction (kg CO₂):", round(carbon_saved.sum(),2))

# Sustainability Impact
st.subheader("🌱 Sustainability Impact")

st.write("Water Saved (Billion m3):", round(water_saved.sum(), 2))
st.write("Estimated Electricity Savings (kWh):", round(electricity_saved.sum(), 2))
st.write("Estimated Carbon Reduction (kg CO₂):", round(carbon_saved.sum(), 2))

st.success("This AI system demonstrates how predictive analytics can support sustainable water management.")